language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install -g gitbook-cli
  - gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _book
  target_branch: gh-pages
  on:
    branch: master
